<?php 
session_start();
if($_SERVER["REQUEST_METHOD"]=="POST")
{
  if(isset($_POST['Add_To_Cart']))
  {
    if(isset($_SESSION['cart']))
    {
      $myitems=array_column($_SESSION['cart'],'proname');
      if(in_array($_POST['proname'],$myitems))
      {
        header("location:shop.php");
      }
      else
      {
        $count=count($_SESSION['cart']);
        $_SESSION['cart'][$count]=array('proname'=>$_POST['proname'],'proprice'=>$_POST['proprice'],'proqty'=>1);
        header("location:shop.php");
      }
    }
    else
    {
      $_SESSION['cart'][0]=array('proname'=>$_POST['proname'],'proprice'=>$_POST['proprice'],'proqty'=>1);
      header("location:shop.php");
    }
  }
  if(isset($_POST['Remove_Item']))
  {
    foreach($_SESSION['cart'] as $key => $value)
    {
      if($value['proname']==$_POST['proname'])
      {
        unset($_SESSION['cart'][$key]);
        $_SESSION['cart']=array_values($_SESSION['cart']);
        echo"<script>
          window.location.href='cart.php';
        </script>";
      }
    }
  }
  if(isset($_POST['Mod_proqty']))
  {
    foreach($_SESSION['cart'] as $key => $value)
    {
      if($value['proname']==$_POST['proname'])
      {
        $_SESSION['cart'][$key]['proqty']=$_POST['Mod_proqty'];
        echo"<script>
          window.location.href='cart.php';
        </script>";
      }
    }
  }
}

?>